// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW8rrrTySwOGPQc7-JUyy9tQ56PKLRvO4',
    appId: '1:315765399489:web:977f6e02be3fb8c27e1940',
    messagingSenderId: '315765399489',
    projectId: 'mygym-9b67b',
    authDomain: 'mygym-9b67b.firebaseapp.com',
    storageBucket: 'mygym-9b67b.firebasestorage.app',
    measurementId: 'G-JJR88BRKF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx4_qdsUClz2wVAoz-UB7-_yAaJZ801r0',
    appId: '1:315765399489:android:572c7a6b0852a6ef7e1940',
    messagingSenderId: '315765399489',
    projectId: 'mygym-9b67b',
    storageBucket: 'mygym-9b67b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeQsMKl9P0BLZz245oNRHcgo7Sf1_zspU',
    appId: '1:315765399489:ios:bc3dd311d05e8ea97e1940',
    messagingSenderId: '315765399489',
    projectId: 'mygym-9b67b',
    storageBucket: 'mygym-9b67b.firebasestorage.app',
    iosBundleId: 'com.example.mygym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeQsMKl9P0BLZz245oNRHcgo7Sf1_zspU',
    appId: '1:315765399489:ios:bc3dd311d05e8ea97e1940',
    messagingSenderId: '315765399489',
    projectId: 'mygym-9b67b',
    storageBucket: 'mygym-9b67b.firebasestorage.app',
    iosBundleId: 'com.example.mygym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW8rrrTySwOGPQc7-JUyy9tQ56PKLRvO4',
    appId: '1:315765399489:web:893fd13c8d83b1137e1940',
    messagingSenderId: '315765399489',
    projectId: 'mygym-9b67b',
    authDomain: 'mygym-9b67b.firebaseapp.com',
    storageBucket: 'mygym-9b67b.firebasestorage.app',
    measurementId: 'G-8KHL8YQLHD',
  );

}